#include <exception>

#include "dfa.h"

int DFA::get_int_representation(State state)
{
	switch (state)
	{
		case State::one:
		case State::one_l:
			return 1;
		case State::two:
		case State::two_l:
			return 2;
		case State::three:
		case State::three_l:
			return 3;
		case State::four:
		case State::four_l:
			return 4;
		case State::five:
		case State::five_l:
			return 5;
		case State::six:
		case State::six_l:
			return 6;
		case State::seven:
		case State::seven_l:
			return 7;
		case State::eight:
		case State::eight_l:
			return 8;
		case State::nine:
		case State::nine_l:
			return 9;
		case State::zero:
		case State::zero_l:
			return 0;
		default:
			throw std::exception();
	}
};

bool DFA::is_accepting(State state)
{
	switch (state)
	{
		case State::one:
		case State::two:
		case State::three:
		case State::four:
		case State::five:
		case State::six:
		case State::seven:
		case State::eight:
		case State::nine:
		case State::zero:
		case State::one_l:
		case State::two_l:
		case State::three_l:
		case State::four_l:
		case State::five_l:
		case State::six_l:
		case State::seven_l:
		case State::eight_l:
		case State::nine_l:
		case State::zero_l:
			return true;
		default:
			return false;
	}
}

DFA::State DFA::transition(State start_state, char input)
{
	switch (start_state)
	{
		case State::start:
			switch (input)
			{
				case 'o':
					return State::o;
				case 't':
					return State::t;
				case 'f':
					return State::f;
				case 's':
					return State::s;
				case 'e':
					return State::e;
				case 'n':
					return State::n;
				case 'z':
					return State::z;
				case '1':
					return State::one_l;
				case '2':
					return State::two_l;
				case '3':
					return State::three_l;
				case '4':
					return State::four_l;
				case '5':
					return State::five_l;
				case '6':
					return State::six_l;
				case '7':
					return State::seven_l;
				case '8':
					return State::eight_l;
				case '9':
					return State::nine_l;
				case '0':
					return State::zero_l;
				default:
					return State::start;
			}
		case State::o:
			switch (input)
			{
				case 'n':
					return State::on;
				case 'o':
					return State::o;
				case 't':
					return State::t;
				case 'f':
					return State::f;
				case 's':
					return State::s;
				case 'e':
					return State::e;
				case 'z':
					return State::z;
				case '1':
					return State::one_l;
				case '2':
					return State::two_l;
				case '3':
					return State::three_l;
				case '4':
					return State::four_l;
				case '5':
					return State::five_l;
				case '6':
					return State::six_l;
				case '7':
					return State::seven_l;
				case '8':
					return State::eight_l;
				case '9':
					return State::nine_l;
				case '0':
					return State::zero_l;
				default:
					return State::start;
			}
		case State::on:
			switch (input)
			{
				case 'e':
					return State::one;
				case 'i':
					return State::ni;
				case 'o':
					return State::o;
				case 't':
					return State::t;
				case 'f':
					return State::f;
				case 's':
					return State::s;
				case 'n':
					return State::n;
				case 'z':
					return State::z;
				case '1':
					return State::one_l;
				case '2':
					return State::two_l;
				case '3':
					return State::three_l;
				case '4':
					return State::four_l;
				case '5':
					return State::five_l;
				case '6':
					return State::six_l;
				case '7':
					return State::seven_l;
				case '8':
					return State::eight_l;
				case '9':
					return State::nine_l;
				case '0':
					return State::zero_l;
				default:
					return State::start;
			}
		case State::one:
			switch (input)
			{
				case 'i':
					return State::ei;
				case 'o':
					return State::o;
				case 't':
					return State::t;
				case 'f':
					return State::f;
				case 's':
					return State::s;
				case 'e':
					return State::e;
				case 'n':
					return State::n;
				case 'z':
					return State::z;
				case '1':
					return State::one_l;
				case '2':
					return State::two_l;
				case '3':
					return State::three_l;
				case '4':
					return State::four_l;
				case '5':
					return State::five_l;
				case '6':
					return State::six_l;
				case '7':
					return State::seven_l;
				case '8':
					return State::eight_l;
				case '9':
					return State::nine_l;
				case '0':
					return State::zero_l;
				default:
					return State::start;
			}
		case State::t:
			switch (input)
			{
				case 'w':
					return State::tw;
				case 'h':
					return State::th;
				case 'o':
					return State::o;
				case 't':
					return State::t;
				case 'f':
					return State::f;
				case 's':
					return State::s;
				case 'e':
					return State::e;
				case 'n':
					return State::n;
				case 'z':
					return State::z;
				case '1':
					return State::one_l;
				case '2':
					return State::two_l;
				case '3':
					return State::three_l;
				case '4':
					return State::four_l;
				case '5':
					return State::five_l;
				case '6':
					return State::six_l;
				case '7':
					return State::seven_l;
				case '8':
					return State::eight_l;
				case '9':
					return State::nine_l;
				case '0':
					return State::zero_l;
				default:
					return State::start;
			}
		case State::tw:
			switch (input)
			{
				case 'o':
					return State::two;
				case 't':
					return State::t;
				case 'f':
					return State::f;
				case 's':
					return State::s;
				case 'e':
					return State::e;
				case 'n':
					return State::n;
				case 'z':
					return State::z;
				case '1':
					return State::one_l;
				case '2':
					return State::two_l;
				case '3':
					return State::three_l;
				case '4':
					return State::four_l;
				case '5':
					return State::five_l;
				case '6':
					return State::six_l;
				case '7':
					return State::seven_l;
				case '8':
					return State::eight_l;
				case '9':
					return State::nine_l;
				case '0':
					return State::zero_l;
				default:
					return State::start;
			}
		case State::two:
			switch (input)
			{
				case 'n':
					return State::on;
				case 'o':
					return State::o;
				case 't':
					return State::t;
				case 'f':
					return State::f;
				case 's':
					return State::s;
				case 'e':
					return State::e;
				case 'z':
					return State::z;
				case '1':
					return State::one_l;
				case '2':
					return State::two_l;
				case '3':
					return State::three_l;
				case '4':
					return State::four_l;
				case '5':
					return State::five_l;
				case '6':
					return State::six_l;
				case '7':
					return State::seven_l;
				case '8':
					return State::eight_l;
				case '9':
					return State::nine_l;
				case '0':
					return State::zero_l;
				default:
					return State::start;
			}
		case State::th:
			switch (input)
			{
				case 'r':
					return State::thr;
				case 'o':
					return State::o;
				case 't':
					return State::t;
				case 'f':
					return State::f;
				case 's':
					return State::s;
				case 'e':
					return State::e;
				case 'n':
					return State::n;
				case 'z':
					return State::z;
				case '1':
					return State::one_l;
				case '2':
					return State::two_l;
				case '3':
					return State::three_l;
				case '4':
					return State::four_l;
				case '5':
					return State::five_l;
				case '6':
					return State::six_l;
				case '7':
					return State::seven_l;
				case '8':
					return State::eight_l;
				case '9':
					return State::nine_l;
				case '0':
					return State::zero_l;
				default:
					return State::start;
			}
		case State::thr:
			switch (input)
			{
				case 'e':
					return State::thre;
				case 'o':
					return State::o;
				case 't':
					return State::t;
				case 'f':
					return State::f;
				case 's':
					return State::s;
				case 'n':
					return State::n;
				case 'z':
					return State::z;
				case '1':
					return State::one_l;
				case '2':
					return State::two_l;
				case '3':
					return State::three_l;
				case '4':
					return State::four_l;
				case '5':
					return State::five_l;
				case '6':
					return State::six_l;
				case '7':
					return State::seven_l;
				case '8':
					return State::eight_l;
				case '9':
					return State::nine_l;
				case '0':
					return State::zero_l;
				default:
					return State::start;
			}
		case State::thre:
			switch (input)
			{
				case 'e':
					return State::three;
				case 'i':
					return State::ei;
				case 'o':
					return State::o;
				case 't':
					return State::t;
				case 'f':
					return State::f;
				case 's':
					return State::s;
				case 'n':
					return State::n;
				case 'z':
					return State::z;
				case '1':
					return State::one_l;
				case '2':
					return State::two_l;
				case '3':
					return State::three_l;
				case '4':
					return State::four_l;
				case '5':
					return State::five_l;
				case '6':
					return State::six_l;
				case '7':
					return State::seven_l;
				case '8':
					return State::eight_l;
				case '9':
					return State::nine_l;
				case '0':
					return State::zero_l;
				default:
					return State::start;
			}
		case State::three:
			switch (input)
			{
				case 'i':
					return State::ei;
				case 'o':
					return State::o;
				case 't':
					return State::t;
				case 'f':
					return State::f;
				case 's':
					return State::s;
				case 'e':
					return State::e;
				case 'n':
					return State::n;
				case 'z':
					return State::z;
				case '1':
					return State::one_l;
				case '2':
					return State::two_l;
				case '3':
					return State::three_l;
				case '4':
					return State::four_l;
				case '5':
					return State::five_l;
				case '6':
					return State::six_l;
				case '7':
					return State::seven_l;
				case '8':
					return State::eight_l;
				case '9':
					return State::nine_l;
				case '0':
					return State::zero_l;
				default:
					return State::start;
			}
		case State::f:
			switch (input)
			{
				case 'o':
					return State::fo;
				case 'i':
					return State::fi;
				case 't':
					return State::t;
				case 'f':
					return State::f;
				case 's':
					return State::s;
				case 'e':
					return State::e;
				case 'n':
					return State::n;
				case 'z':
					return State::z;
				case '1':
					return State::one_l;
				case '2':
					return State::two_l;
				case '3':
					return State::three_l;
				case '4':
					return State::four_l;
				case '5':
					return State::five_l;
				case '6':
					return State::six_l;
				case '7':
					return State::seven_l;
				case '8':
					return State::eight_l;
				case '9':
					return State::nine_l;
				case '0':
					return State::zero_l;
				default:
					return State::start;
			}
		case State::fo:
			switch (input)
			{
				case 'u':
					return State::fou;
				case 'n':
					return State::on;
				case 'o':
					return State::o;
				case 't':
					return State::t;
				case 'f':
					return State::f;
				case 's':
					return State::s;
				case 'e':
					return State::e;
				case 'z':
					return State::z;
				case '1':
					return State::one_l;
				case '2':
					return State::two_l;
				case '3':
					return State::three_l;
				case '4':
					return State::four_l;
				case '5':
					return State::five_l;
				case '6':
					return State::six_l;
				case '7':
					return State::seven_l;
				case '8':
					return State::eight_l;
				case '9':
					return State::nine_l;
				case '0':
					return State::zero_l;
				default:
					return State::start;
			}
		case State::fou:
			switch (input)
			{
				case 'r':
					return State::four;
				case 'o':
					return State::o;
				case 't':
					return State::t;
				case 'f':
					return State::f;
				case 's':
					return State::s;
				case 'e':
					return State::e;
				case 'n':
					return State::n;
				case 'z':
					return State::z;
				case '1':
					return State::one_l;
				case '2':
					return State::two_l;
				case '3':
					return State::three_l;
				case '4':
					return State::four_l;
				case '5':
					return State::five_l;
				case '6':
					return State::six_l;
				case '7':
					return State::seven_l;
				case '8':
					return State::eight_l;
				case '9':
					return State::nine_l;
				case '0':
					return State::zero_l;
				default:
					return State::start;
			}
		case State::four:
			switch (input)
			{
				case 'o':
					return State::o;
				case 't':
					return State::t;
				case 'f':
					return State::f;
				case 's':
					return State::s;
				case 'e':
					return State::e;
				case 'n':
					return State::n;
				case 'z':
					return State::z;
				case '1':
					return State::one_l;
				case '2':
					return State::two_l;
				case '3':
					return State::three_l;
				case '4':
					return State::four_l;
				case '5':
					return State::five_l;
				case '6':
					return State::six_l;
				case '7':
					return State::seven_l;
				case '8':
					return State::eight_l;
				case '9':
					return State::nine_l;
				case '0':
					return State::zero_l;
				default:
					return State::start;
			}
		case State::fi:
			switch (input)
			{
				case 'v':
					return State::fiv;
				case 'o':
					return State::o;
				case 't':
					return State::t;
				case 'f':
					return State::f;
				case 's':
					return State::s;
				case 'e':
					return State::e;
				case 'n':
					return State::n;
				case 'z':
					return State::z;
				case '1':
					return State::one_l;
				case '2':
					return State::two_l;
				case '3':
					return State::three_l;
				case '4':
					return State::four_l;
				case '5':
					return State::five_l;
				case '6':
					return State::six_l;
				case '7':
					return State::seven_l;
				case '8':
					return State::eight_l;
				case '9':
					return State::nine_l;
				case '0':
					return State::zero_l;
				default:
					return State::start;
			}
		case State::fiv:
			switch (input)
			{
				case 'e':
					return State::five;
				case 'o':
					return State::o;
				case 't':
					return State::t;
				case 'f':
					return State::f;
				case 's':
					return State::s;
				case 'n':
					return State::n;
				case 'z':
					return State::z;
				case '1':
					return State::one_l;
				case '2':
					return State::two_l;
				case '3':
					return State::three_l;
				case '4':
					return State::four_l;
				case '5':
					return State::five_l;
				case '6':
					return State::six_l;
				case '7':
					return State::seven_l;
				case '8':
					return State::eight_l;
				case '9':
					return State::nine_l;
				case '0':
					return State::zero_l;
				default:
					return State::start;
			}
		case State::five:
			switch (input)
			{
				case 'i':
					return State::ei;
				case 'o':
					return State::o;
				case 't':
					return State::t;
				case 'f':
					return State::f;
				case 's':
					return State::s;
				case 'e':
					return State::e;
				case 'n':
					return State::n;
				case 'z':
					return State::z;
				case '1':
					return State::one_l;
				case '2':
					return State::two_l;
				case '3':
					return State::three_l;
				case '4':
					return State::four_l;
				case '5':
					return State::five_l;
				case '6':
					return State::six_l;
				case '7':
					return State::seven_l;
				case '8':
					return State::eight_l;
				case '9':
					return State::nine_l;
				case '0':
					return State::zero_l;
				default:
					return State::start;
			}
		case State::s:
			switch (input)
			{
				case 'i':
					return State::si;
				case 'e':
					return State::se;
				case 'o':
					return State::o;
				case 't':
					return State::t;
				case 'f':
					return State::f;
				case 's':
					return State::s;
				case 'n':
					return State::n;
				case 'z':
					return State::z;
				case '1':
					return State::one_l;
				case '2':
					return State::two_l;
				case '3':
					return State::three_l;
				case '4':
					return State::four_l;
				case '5':
					return State::five_l;
				case '6':
					return State::six_l;
				case '7':
					return State::seven_l;
				case '8':
					return State::eight_l;
				case '9':
					return State::nine_l;
				case '0':
					return State::zero_l;
				default:
					return State::start;
			}
		case State::si:
			switch (input)
			{
				case 'x':
					return State::six;
				case 'o':
					return State::o;
				case 't':
					return State::t;
				case 'f':
					return State::f;
				case 's':
					return State::s;
				case 'e':
					return State::e;
				case 'n':
					return State::n;
				case 'z':
					return State::z;
				case '1':
					return State::one_l;
				case '2':
					return State::two_l;
				case '3':
					return State::three_l;
				case '4':
					return State::four_l;
				case '5':
					return State::five_l;
				case '6':
					return State::six_l;
				case '7':
					return State::seven_l;
				case '8':
					return State::eight_l;
				case '9':
					return State::nine_l;
				case '0':
					return State::zero_l;
				default:
					return State::start;
			}
		case State::six:
			switch (input)
			{
				case 'o':
					return State::o;
				case 't':
					return State::t;
				case 'f':
					return State::f;
				case 's':
					return State::s;
				case 'e':
					return State::e;
				case 'n':
					return State::n;
				case 'z':
					return State::z;
				case '1':
					return State::one_l;
				case '2':
					return State::two_l;
				case '3':
					return State::three_l;
				case '4':
					return State::four_l;
				case '5':
					return State::five_l;
				case '6':
					return State::six_l;
				case '7':
					return State::seven_l;
				case '8':
					return State::eight_l;
				case '9':
					return State::nine_l;
				case '0':
					return State::zero_l;
				default:
					return State::start;
			}
		case State::se:
			switch (input)
			{
				case 'v':
					return State::sev;
				case 'i':
					return State::ei;
				case 'o':
					return State::o;
				case 't':
					return State::t;
				case 'f':
					return State::f;
				case 's':
					return State::s;
				case 'e':
					return State::e;
				case 'n':
					return State::n;
				case 'z':
					return State::z;
				case '1':
					return State::one_l;
				case '2':
					return State::two_l;
				case '3':
					return State::three_l;
				case '4':
					return State::four_l;
				case '5':
					return State::five_l;
				case '6':
					return State::six_l;
				case '7':
					return State::seven_l;
				case '8':
					return State::eight_l;
				case '9':
					return State::nine_l;
				case '0':
					return State::zero_l;
				default:
					return State::start;
			}
		case State::sev:
			switch (input)
			{
				case 'e':
					return State::seve;
				case 'o':
					return State::o;
				case 't':
					return State::t;
				case 'f':
					return State::f;
				case 's':
					return State::s;
				case 'n':
					return State::n;
				case 'z':
					return State::z;
				case '1':
					return State::one_l;
				case '2':
					return State::two_l;
				case '3':
					return State::three_l;
				case '4':
					return State::four_l;
				case '5':
					return State::five_l;
				case '6':
					return State::six_l;
				case '7':
					return State::seven_l;
				case '8':
					return State::eight_l;
				case '9':
					return State::nine_l;
				case '0':
					return State::zero_l;
				default:
					return State::start;
			}
		case State::seve:
			switch (input)
			{
				case 'n':
					return State::seven;
				case 'i':
					return State::ei;
				case 'o':
					return State::o;
				case 't':
					return State::t;
				case 'f':
					return State::f;
				case 's':
					return State::s;
				case 'e':
					return State::e;
				case 'z':
					return State::z;
				case '1':
					return State::one_l;
				case '2':
					return State::two_l;
				case '3':
					return State::three_l;
				case '4':
					return State::four_l;
				case '5':
					return State::five_l;
				case '6':
					return State::six_l;
				case '7':
					return State::seven_l;
				case '8':
					return State::eight_l;
				case '9':
					return State::nine_l;
				case '0':
					return State::zero_l;
				default:
					return State::start;
			}
		case State::seven:
			switch (input)
			{
				case 'i':
					return State::ni;
				case 'o':
					return State::o;
				case 't':
					return State::t;
				case 'f':
					return State::f;
				case 's':
					return State::s;
				case 'e':
					return State::e;
				case 'n':
					return State::n;
				case 'z':
					return State::z;
				case '1':
					return State::one_l;
				case '2':
					return State::two_l;
				case '3':
					return State::three_l;
				case '4':
					return State::four_l;
				case '5':
					return State::five_l;
				case '6':
					return State::six_l;
				case '7':
					return State::seven_l;
				case '8':
					return State::eight_l;
				case '9':
					return State::nine_l;
				case '0':
					return State::zero_l;
				default:
					return State::start;
			}
		case State::e:
			switch (input)
			{
				case 'i':
					return State::ei;
				case 'o':
					return State::o;
				case 't':
					return State::t;
				case 'f':
					return State::f;
				case 's':
					return State::s;
				case 'e':
					return State::e;
				case 'n':
					return State::n;
				case 'z':
					return State::z;
				case '1':
					return State::one_l;
				case '2':
					return State::two_l;
				case '3':
					return State::three_l;
				case '4':
					return State::four_l;
				case '5':
					return State::five_l;
				case '6':
					return State::six_l;
				case '7':
					return State::seven_l;
				case '8':
					return State::eight_l;
				case '9':
					return State::nine_l;
				case '0':
					return State::zero_l;
				default:
					return State::start;
			}
		case State::ei:
			switch (input)
			{
				case 'g':
					return State::eig;
				case 'o':
					return State::o;
				case 't':
					return State::t;
				case 'f':
					return State::f;
				case 's':
					return State::s;
				case 'e':
					return State::e;
				case 'n':
					return State::n;
				case 'z':
					return State::z;
				case '1':
					return State::one_l;
				case '2':
					return State::two_l;
				case '3':
					return State::three_l;
				case '4':
					return State::four_l;
				case '5':
					return State::five_l;
				case '6':
					return State::six_l;
				case '7':
					return State::seven_l;
				case '8':
					return State::eight_l;
				case '9':
					return State::nine_l;
				case '0':
					return State::zero_l;
				default:
					return State::start;
			}
		case State::eig:
			switch (input)
			{
				case 'h':
					return State::eigh;
				case 'o':
					return State::o;
				case 't':
					return State::t;
				case 'f':
					return State::f;
				case 's':
					return State::s;
				case 'e':
					return State::e;
				case 'n':
					return State::n;
				case 'z':
					return State::z;
				case '1':
					return State::one_l;
				case '2':
					return State::two_l;
				case '3':
					return State::three_l;
				case '4':
					return State::four_l;
				case '5':
					return State::five_l;
				case '6':
					return State::six_l;
				case '7':
					return State::seven_l;
				case '8':
					return State::eight_l;
				case '9':
					return State::nine_l;
				case '0':
					return State::zero_l;
				default:
					return State::start;
			}
		case State::eigh:
			switch (input)
			{
				case 't':
					return State::eight;
				case 'o':
					return State::o;
				case 'f':
					return State::f;
				case 's':
					return State::s;
				case 'e':
					return State::e;
				case 'n':
					return State::n;
				case 'z':
					return State::z;
				case '1':
					return State::one_l;
				case '2':
					return State::two_l;
				case '3':
					return State::three_l;
				case '4':
					return State::four_l;
				case '5':
					return State::five_l;
				case '6':
					return State::six_l;
				case '7':
					return State::seven_l;
				case '8':
					return State::eight_l;
				case '9':
					return State::nine_l;
				case '0':
					return State::zero_l;
				default:
					return State::start;
			}
		case State::eight:
			switch (input)
			{
				case 'w':
					return State::tw;
				case 'h':
					return State::th;
				case 'o':
					return State::o;
				case 't':
					return State::t;
				case 'f':
					return State::f;
				case 's':
					return State::s;
				case 'e':
					return State::e;
				case 'n':
					return State::n;
				case 'z':
					return State::z;
				case '1':
					return State::one_l;
				case '2':
					return State::two_l;
				case '3':
					return State::three_l;
				case '4':
					return State::four_l;
				case '5':
					return State::five_l;
				case '6':
					return State::six_l;
				case '7':
					return State::seven_l;
				case '8':
					return State::eight_l;
				case '9':
					return State::nine_l;
				case '0':
					return State::zero_l;
				default:
					return State::start;
			}
		case State::n:
			switch (input)
			{
				case 'i':
					return State::ni;
				case 'o':
					return State::o;
				case 't':
					return State::t;
				case 'f':
					return State::f;
				case 's':
					return State::s;
				case 'e':
					return State::e;
				case 'n':
					return State::n;
				case 'z':
					return State::z;
				case '1':
					return State::one_l;
				case '2':
					return State::two_l;
				case '3':
					return State::three_l;
				case '4':
					return State::four_l;
				case '5':
					return State::five_l;
				case '6':
					return State::six_l;
				case '7':
					return State::seven_l;
				case '8':
					return State::eight_l;
				case '9':
					return State::nine_l;
				case '0':
					return State::zero_l;
				default:
					return State::start;
			}
		case State::ni:
			switch (input)
			{
				case 'n':
					return State::nin;
				case 'o':
					return State::o;
				case 't':
					return State::t;
				case 'f':
					return State::f;
				case 's':
					return State::s;
				case 'e':
					return State::e;
				case 'z':
					return State::z;
				case '1':
					return State::one_l;
				case '2':
					return State::two_l;
				case '3':
					return State::three_l;
				case '4':
					return State::four_l;
				case '5':
					return State::five_l;
				case '6':
					return State::six_l;
				case '7':
					return State::seven_l;
				case '8':
					return State::eight_l;
				case '9':
					return State::nine_l;
				case '0':
					return State::zero_l;
				default:
					return State::start;
			}
		case State::nin:
			switch (input)
			{
				case 'e':
					return State::nine;
				case 'i':
					return State::ni;
				case 'o':
					return State::o;
				case 't':
					return State::t;
				case 'f':
					return State::f;
				case 's':
					return State::s;
				case 'n':
					return State::n;
				case 'z':
					return State::z;
				case '1':
					return State::one_l;
				case '2':
					return State::two_l;
				case '3':
					return State::three_l;
				case '4':
					return State::four_l;
				case '5':
					return State::five_l;
				case '6':
					return State::six_l;
				case '7':
					return State::seven_l;
				case '8':
					return State::eight_l;
				case '9':
					return State::nine_l;
				case '0':
					return State::zero_l;
				default:
					return State::start;
			}
		case State::nine:
			switch (input)
			{
				case 'i':
					return State::ei;
				case 'o':
					return State::o;
				case 't':
					return State::t;
				case 'f':
					return State::f;
				case 's':
					return State::s;
				case 'e':
					return State::e;
				case 'n':
					return State::n;
				case 'z':
					return State::z;
				case '1':
					return State::one_l;
				case '2':
					return State::two_l;
				case '3':
					return State::three_l;
				case '4':
					return State::four_l;
				case '5':
					return State::five_l;
				case '6':
					return State::six_l;
				case '7':
					return State::seven_l;
				case '8':
					return State::eight_l;
				case '9':
					return State::nine_l;
				case '0':
					return State::zero_l;
				default:
					return State::start;
			}
		case State::z:
			switch (input)
			{
				case 'e':
					return State::ze;
				case 'o':
					return State::o;
				case 't':
					return State::t;
				case 'f':
					return State::f;
				case 's':
					return State::s;
				case 'n':
					return State::n;
				case 'z':
					return State::z;
				case '1':
					return State::one_l;
				case '2':
					return State::two_l;
				case '3':
					return State::three_l;
				case '4':
					return State::four_l;
				case '5':
					return State::five_l;
				case '6':
					return State::six_l;
				case '7':
					return State::seven_l;
				case '8':
					return State::eight_l;
				case '9':
					return State::nine_l;
				case '0':
					return State::zero_l;
				default:
					return State::start;
			}
		case State::ze:
			switch (input)
			{
				case 'r':
					return State::zer;
				case 'i':
					return State::ei;
				case 'o':
					return State::o;
				case 't':
					return State::t;
				case 'f':
					return State::f;
				case 's':
					return State::s;
				case 'e':
					return State::e;
				case 'n':
					return State::n;
				case 'z':
					return State::z;
				case '1':
					return State::one_l;
				case '2':
					return State::two_l;
				case '3':
					return State::three_l;
				case '4':
					return State::four_l;
				case '5':
					return State::five_l;
				case '6':
					return State::six_l;
				case '7':
					return State::seven_l;
				case '8':
					return State::eight_l;
				case '9':
					return State::nine_l;
				case '0':
					return State::zero_l;
				default:
					return State::start;
			}
		case State::zer:
			switch (input)
			{
				case 'o':
					return State::zero;
				case 't':
					return State::t;
				case 'f':
					return State::f;
				case 's':
					return State::s;
				case 'e':
					return State::e;
				case 'n':
					return State::n;
				case 'z':
					return State::z;
				case '1':
					return State::one_l;
				case '2':
					return State::two_l;
				case '3':
					return State::three_l;
				case '4':
					return State::four_l;
				case '5':
					return State::five_l;
				case '6':
					return State::six_l;
				case '7':
					return State::seven_l;
				case '8':
					return State::eight_l;
				case '9':
					return State::nine_l;
				case '0':
					return State::zero_l;
				default:
					return State::start;
			}
		case State::zero:
			switch (input)
			{
				case 'n':
					return State::on;
				case 'o':
					return State::o;
				case 't':
					return State::t;
				case 'f':
					return State::f;
				case 's':
					return State::s;
				case 'e':
					return State::e;
				case 'z':
					return State::z;
				case '1':
					return State::one_l;
				case '2':
					return State::two_l;
				case '3':
					return State::three_l;
				case '4':
					return State::four_l;
				case '5':
					return State::five_l;
				case '6':
					return State::six_l;
				case '7':
					return State::seven_l;
				case '8':
					return State::eight_l;
				case '9':
					return State::nine_l;
				case '0':
					return State::zero_l;
				default:
					return State::start;
			}
		case State::one_l:
			switch (input)
			{
				case 'o':
					return State::o;
				case 't':
					return State::t;
				case 'f':
					return State::f;
				case 's':
					return State::s;
				case 'e':
					return State::e;
				case 'n':
					return State::n;
				case 'z':
					return State::z;
				case '1':
					return State::one_l;
				case '2':
					return State::two_l;
				case '3':
					return State::three_l;
				case '4':
					return State::four_l;
				case '5':
					return State::five_l;
				case '6':
					return State::six_l;
				case '7':
					return State::seven_l;
				case '8':
					return State::eight_l;
				case '9':
					return State::nine_l;
				case '0':
					return State::zero_l;
				default:
					return State::start;
			}
		case State::two_l:
			switch (input)
			{
				case 'o':
					return State::o;
				case 't':
					return State::t;
				case 'f':
					return State::f;
				case 's':
					return State::s;
				case 'e':
					return State::e;
				case 'n':
					return State::n;
				case 'z':
					return State::z;
				case '1':
					return State::one_l;
				case '2':
					return State::two_l;
				case '3':
					return State::three_l;
				case '4':
					return State::four_l;
				case '5':
					return State::five_l;
				case '6':
					return State::six_l;
				case '7':
					return State::seven_l;
				case '8':
					return State::eight_l;
				case '9':
					return State::nine_l;
				case '0':
					return State::zero_l;
				default:
					return State::start;
			}
		case State::three_l:
			switch (input)
			{
				case 'o':
					return State::o;
				case 't':
					return State::t;
				case 'f':
					return State::f;
				case 's':
					return State::s;
				case 'e':
					return State::e;
				case 'n':
					return State::n;
				case 'z':
					return State::z;
				case '1':
					return State::one_l;
				case '2':
					return State::two_l;
				case '3':
					return State::three_l;
				case '4':
					return State::four_l;
				case '5':
					return State::five_l;
				case '6':
					return State::six_l;
				case '7':
					return State::seven_l;
				case '8':
					return State::eight_l;
				case '9':
					return State::nine_l;
				case '0':
					return State::zero_l;
				default:
					return State::start;
			}
		case State::four_l:
			switch (input)
			{
				case 'o':
					return State::o;
				case 't':
					return State::t;
				case 'f':
					return State::f;
				case 's':
					return State::s;
				case 'e':
					return State::e;
				case 'n':
					return State::n;
				case 'z':
					return State::z;
				case '1':
					return State::one_l;
				case '2':
					return State::two_l;
				case '3':
					return State::three_l;
				case '4':
					return State::four_l;
				case '5':
					return State::five_l;
				case '6':
					return State::six_l;
				case '7':
					return State::seven_l;
				case '8':
					return State::eight_l;
				case '9':
					return State::nine_l;
				case '0':
					return State::zero_l;
				default:
					return State::start;
			}
		case State::five_l:
			switch (input)
			{
				case 'o':
					return State::o;
				case 't':
					return State::t;
				case 'f':
					return State::f;
				case 's':
					return State::s;
				case 'e':
					return State::e;
				case 'n':
					return State::n;
				case 'z':
					return State::z;
				case '1':
					return State::one_l;
				case '2':
					return State::two_l;
				case '3':
					return State::three_l;
				case '4':
					return State::four_l;
				case '5':
					return State::five_l;
				case '6':
					return State::six_l;
				case '7':
					return State::seven_l;
				case '8':
					return State::eight_l;
				case '9':
					return State::nine_l;
				case '0':
					return State::zero_l;
				default:
					return State::start;
			}
		case State::six_l:
			switch (input)
			{
				case 'o':
					return State::o;
				case 't':
					return State::t;
				case 'f':
					return State::f;
				case 's':
					return State::s;
				case 'e':
					return State::e;
				case 'n':
					return State::n;
				case 'z':
					return State::z;
				case '1':
					return State::one_l;
				case '2':
					return State::two_l;
				case '3':
					return State::three_l;
				case '4':
					return State::four_l;
				case '5':
					return State::five_l;
				case '6':
					return State::six_l;
				case '7':
					return State::seven_l;
				case '8':
					return State::eight_l;
				case '9':
					return State::nine_l;
				case '0':
					return State::zero_l;
				default:
					return State::start;
			}
		case State::seven_l:
			switch (input)
			{
				case 'o':
					return State::o;
				case 't':
					return State::t;
				case 'f':
					return State::f;
				case 's':
					return State::s;
				case 'e':
					return State::e;
				case 'n':
					return State::n;
				case 'z':
					return State::z;
				case '1':
					return State::one_l;
				case '2':
					return State::two_l;
				case '3':
					return State::three_l;
				case '4':
					return State::four_l;
				case '5':
					return State::five_l;
				case '6':
					return State::six_l;
				case '7':
					return State::seven_l;
				case '8':
					return State::eight_l;
				case '9':
					return State::nine_l;
				case '0':
					return State::zero_l;
				default:
					return State::start;
			}
		case State::eight_l:
			switch (input)
			{
				case 'o':
					return State::o;
				case 't':
					return State::t;
				case 'f':
					return State::f;
				case 's':
					return State::s;
				case 'e':
					return State::e;
				case 'n':
					return State::n;
				case 'z':
					return State::z;
				case '1':
					return State::one_l;
				case '2':
					return State::two_l;
				case '3':
					return State::three_l;
				case '4':
					return State::four_l;
				case '5':
					return State::five_l;
				case '6':
					return State::six_l;
				case '7':
					return State::seven_l;
				case '8':
					return State::eight_l;
				case '9':
					return State::nine_l;
				case '0':
					return State::zero_l;
				default:
					return State::start;
			}
		case State::nine_l:
			switch (input)
			{
				case 'o':
					return State::o;
				case 't':
					return State::t;
				case 'f':
					return State::f;
				case 's':
					return State::s;
				case 'e':
					return State::e;
				case 'n':
					return State::n;
				case 'z':
					return State::z;
				case '1':
					return State::one_l;
				case '2':
					return State::two_l;
				case '3':
					return State::three_l;
				case '4':
					return State::four_l;
				case '5':
					return State::five_l;
				case '6':
					return State::six_l;
				case '7':
					return State::seven_l;
				case '8':
					return State::eight_l;
				case '9':
					return State::nine_l;
				case '0':
					return State::zero_l;
				default:
					return State::start;
			}
		case State::zero_l:
			switch (input)
			{
				case 'o':
					return State::o;
				case 't':
					return State::t;
				case 'f':
					return State::f;
				case 's':
					return State::s;
				case 'e':
					return State::e;
				case 'n':
					return State::n;
				case 'z':
					return State::z;
				case '1':
					return State::one_l;
				case '2':
					return State::two_l;
				case '3':
					return State::three_l;
				case '4':
					return State::four_l;
				case '5':
					return State::five_l;
				case '6':
					return State::six_l;
				case '7':
					return State::seven_l;
				case '8':
					return State::eight_l;
				case '9':
					return State::nine_l;
				case '0':
					return State::zero_l;
				default:
					return State::start;
			}
	}

	throw std::exception();
}

